/* A packrat parser generated by PackCC 1.8.0 */

#ifndef PCC_INCLUDED_PCC_H
#define PCC_INCLUDED_PCC_H

#include "ast.h"

typedef struct
{
    size_t len;
    const char *str;
} auxil_t;

ast_node_t *pcc_parse_string(const char *str, size_t len);
#ifdef __cplusplus
extern "C" {
#endif

typedef struct pcc_context_tag pcc_context_t;

pcc_context_t *pcc_create(auxil_t *auxil);
int pcc_parse(pcc_context_t *ctx, ast_node_t **ret);
void pcc_destroy(pcc_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_PCC_H */
