/* A packrat parser generated by PackCC 1.8.0 */

#ifndef PCC_INCLUDED_PCC_H
#define PCC_INCLUDED_PCC_H

#include "ast.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct pcc_context_tag pcc_context_t;

pcc_context_t *pcc_create(void *auxil);
int pcc_parse(pcc_context_t *ctx, ast_node_t **ret);
void pcc_destroy(pcc_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_PCC_H */
